apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-versions.yaml
  - ../../groups/all
  - ../../groups/prod

helmGlobals:
  chartHome: ../../.helm-charts

helmCharts:
- name: argocd-app-of-app
  valuesFile: values.yaml
  namespace: openshift-gitops


replacements:
- source:
    version: v1
    kind: ConfigMap
    name: cluster-versions
    fieldPath: data.etl6
  targets:
  - select:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    fieldPaths:
    - spec.source.targetRevision
