      
projects: {}

applications: 

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl6/overlays/nmstate-configuration

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl6/overlays/trident-configuration

  # ibm-fusion-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: ibm-spectrum-fusion-ns
  #   source:
  #     path: clusters/etl6/overlays/ibm-fusion-configuration
  #   extraFields: |
  #     ignoreDifferences:
  #       - group: 'service.isf.ibm.com'
  #         jsonPointers:
  #           - /spec/doInstall
  #         kind: FusionServiceInstance      

# HA

  node-health-check-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-workload-availability
    source:
      path: clusters/etl6/overlays/node-health-check-configuration  

# Observability

  power-monitoring-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl6/overlays/power-monitoring-configuration      

# VMs 

  vm-tests:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: vm-tests
    source:
      path: clusters/etl6/overlays/vm-tests

  trilio-vm-tests:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: trilio-vm-tests
    source:
      path: clusters/etl6/overlays/trilio-vm-tests
    extraFields: |
      ignoreDifferences:
        - group: 'triliovault.trilio.io'
          jsonPointers:
            - /spec/objectStoreCredentials/credentialSecret/resourceVersion
            - /spec/objectStoreCredentials/credentialSecret/uid
          kind: Target            