apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Cluster
metadata:
  name: ibm-spectrum-scale
spec:
  daemon:
    clusterProfile:
      cloudEnv: general
      ignoreReplicaSpaceOnStat: 'yes'
      ignoreReplicationForQuota: 'yes'
      ignoreReplicationOnStatfs: 'yes'
      readReplicaPolicy: local
      traceGenSubDir: /var/mmfs/tmp/traces
      tscCmdPortRange: 60000-61000
    nodeSelector:
      scale.spectrum.ibm.com/role: storage
    nsdDevicesConfig:
      bypassDiscovery: true
    update:
      paused: false
    roles:
    - name: client
      limits: {}
      profile: {}
      resources:
        cpu: "2"
        memory: 4Gi
    - name: storage
      limits: {}
      profile: {}    
      resources:
        cpu: "2"
        memory: 16Gi   
  gui:
    enableSessionIPCheck: true             
  license:
    accept: true
    license: data-management
  pmcollector:
    storageClass: "ontap-nas"
    nodeSelector:
      scale.spectrum.ibm.com/role: storage