apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ibm-spectrum-scale

resources:
  - ./cluster.yaml
  - ./fusion-access.yaml
  - ./filesystem.yaml
  - ./local-disk.yaml
  - ./snapshot-class.yaml