apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fusion-access-main
parameters:
  volBackendFs: main
provisioner: spectrumscale.csi.ibm.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true