apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
kind: FenceAgentsRemediationTemplate
metadata:
  name: main-remediation
spec:
  template:
    spec:
      remediationStrategy: OutOfServiceTaint
      agent: fence_redfish 
      nodeparameters:
        --ip: {}
      sharedparameters:
        '--action': reboot
        '--ipport': "80"
        '--lanplus': ''
        '--password': labadmin
        '--username': ocpvirt01!
      retrycount: 5
      retryinterval: '5s'
      timeout: '1m0s'