apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: node-problem-detector
    app.kubernetes.io/name: node-problem-detector
  name: node-problem-detector
  namespace: openshift-workload-availability