apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ldap
resources:
  - configmap.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - namespace.yaml
  - rbac.yaml
  - link.yaml
  - certificate.yaml