#VLAN2901: 192.168.90.0/24
#VLAN2911: 192.168.91.0/24
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 2911 via linux Bridge
  name: vlan-2911-iscsi
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-2911-iscsi",
      "type": "bridge",
      "bridge": "linux-br-iscsi",
      "mtu": 1500,
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "192.168.91.1/24"
          }
        ]
      }    
    }        