apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: loki-operator
spec:
  upgradeStrategy: Default
---  
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: loki-operator
spec:
  channel: stable-6.0 
  name: loki-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace