apiVersion: observability.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  collector:
    resources:
      limits:
        cpu : 2000m
        memory: 16Gi
      requests:
        cpu: 100m
        memory: 1Gi
  serviceAccount:
    name: logcollector
  outputs:
  - name: default-lokistack
    type: lokiStack
    lokiStack:
      target:
        name: logging-loki
        namespace: openshift-logging
      authentication:
        token:
          from: serviceAccount
    tls:
      ca:
        key: service-ca.crt
        configMapName: openshift-service-ca.crt
  pipelines:
  - name: main
    outputRefs:
    - default-lokistack
    inputRefs:
    - application
    - infrastructure