[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    'clusters/hub/overlays/vm-dr-test/vms/fedora-vms.yaml',
    'components/trilio-instance/license.yaml',
    'clusters/etl6/overlays/trilio-vm-tests/fedora-vms.yaml',
    'clusters/etl4/overlays/persistent-reservations/vm.yaml'
  ]