[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    'clusters/hub/overlays/vm-dr-test/vms/fedora-vms.yaml'
  ]