apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-dr-role
  namespace: openshift-gitops
data:
# workloads possible values [active|passive]
# volumes possible values [non-replicated|replicated-active|replicated-passive]
  tier1: |-
    workloads:
      etl6: active
      etl7: passive
    volumes:
      etl6: replicated-active
      etl7: replicated-passive  
  tier2: |-
    workloads:
      etl6: active
      etl7: passive
    volumes:
      etl6: replicated-active
      etl7: replicated-passive 
  tier3: |-
    workloads:
      etl6: active
      etl7: passive
    volumes:
      etl6: replicated-active
      etl7: replicated-passive 

 