apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: ovs-br1-multiple-networks
spec:
  desiredState:
    interfaces:
      - ipv4:
          dhcp: true
          enabled: true
        ipv6:
          enabled: false
        name: ovs-br1-host
        state: up
        type: ovs-interface
      - bridge:
          allow-extra-patch-ports: true
          options:
            stp:
              enabled: false
          port:
            - name: ens1f0
            - name: ovs-br1-host
              vlan:
                mode: access
                tag: 1512
        description: |-
          A dedicated OVS bridge with ens1f0 as a port
          allowing VLAN 1512
        ipv4:
          enabled: false
        ipv6:
          enabled: false
        name: ovs-br1
        state: up
        type: ovs-bridge
    ovn:
      bridge-mappings:
        - bridge: ovs-br1
          localnet: vlan-1512
          state: present
  nodeSelector:
    node-role.kubernetes.io/worker: ''



