apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookinfo

resources: 
- namespace.yaml
- https://raw.githubusercontent.com/openshift-service-mesh/istio/release-1.24/samples/bookinfo/platform/kube/bookinfo.yaml
- certificate.yaml
- gateway.yaml
- virtual-service.yaml

helmGlobals:
  chartHome: ../../../../.helm-charts

helmCharts:
  - name: gateway
    releaseName: bookinfo-ingressgateway
    namespace: istio-test
    valuesFile: ingress-gateway-values.yaml