tenant:
  configSecret:
    name: trident-protect-env-configuration
    accessKey: tridentprotect 
    secretKey: tridentprotect   
  configuration:
    name: trident-protect-env-configuration
  name: trident-protect  
  pools:
    - name: pool-0
      servers: 1
      storageClassName: ontap-nas
      # these values are not recommended in production. They are here just to keep the costs constrained.
      volumesPerServer: 1
      size: 500Gi      
  buckets:
    - name: trident-protect
      objectLock: false
  certificate:    
    requestAutoCert: false         

                        