apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: odf-multicluster-orchestrator
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  subscription:
    channel: stable-4.17
    name: odf-multicluster-orchestrator
    namespace: openshift-operators
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: odf-multicluster-orchestrator.v4.17.3-rhodf
  versions: 
    - odf-multicluster-orchestrator.v4.17.3-rhodf