apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole

resources: []

helmCharts:
  - name: postgresql
    namespace: postgresql
    releaseName: postgresql
    repo: https://charts.bitnami.com/bitnami
    valuesInline:
      global:
        postgresql:
          auth:
            username: guacamole
            password: password
            database: guacamole
            postgresPassword: guacamole
  - name: guacamole
    namespace: guacamole
    releaseName: guacamole
    repo: https://charts.beryju.io
    valuesInline: {}
