apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: guacamole

resources: 
- namespace.yaml
- rbac.yaml

helmCharts:
  - name: postgresql
    namespace: guacamole
    releaseName: postgresql
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesInline:
      global:
        postgresql:
          auth:
            username: guacamole
            password: password
            database: guacamole
            postgresPassword: guacamole
        compatibility:
          openshift:
            adaptSecurityContext: "force"
  - name: guacamole
    namespace: guacamole
    releaseName: guacamole
    repo: https://charts.beryju.io
    valuesInline: {}
