apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-ibox
  name: vm-ibox 
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm-ibox1
        creationTimestamp: null
      spec:
        sourceRef:
          kind: DataSource
          name: infinibox-demo-7.3.11.0-cbdev-7.3.11
          namespace: infinidat-appliance
        storage:
          resources:
            requests:
              storage: 200Gi
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-ibox
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: scsi
            name: datavolumedisk1
          interfaces:
            - masquerade: {}
              macAddress: 02:fb:ed:00:00:00            
              model: virtio
              name: default
            - bridge: {}
              model: virtio
              name: data-link1
              macAddress: 02:fb:ed:00:01:62              
            - bridge: {}
              model: virtio
              name: data-link2
              macAddress: 02:fb:ed:00:01:63
            - bridge: {}
              model: virtio
              name: data-link3
              macAddress: 02:fb:ed:00:01:64
            - bridge: {}
              model: virtio
              name: iscsi-link
              macAddress: 02:fb:ed:00:01:65                            
        machine:
          type: "pc-q35-rhel9.4.0"
        resources:
          requests:
            memory: 25Gi
            cpu: '8'
      terminationGracePeriodSeconds: 10
      volumes:
      - dataVolume:
          name: vm-ibox1
        name: datavolumedisk1
      networks:
        - name: default
          pod: {}
        - multus:
            networkName: default/vlan-2901
          name: data-link1
        - multus:
            networkName: default/vlan-2901-1
          name: data-link2          
        - multus:
            networkName: default/vlan-2911
          name: data-link3
        - multus:
            networkName: default/vlan-2911-1
          name: iscsi-link          