apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: isf-catalog
  namespace: openshift-marketplace
spec:
  displayName: ISF Catalog
  image: cp.icr.io/cpopen/isf-operator-software-catalog:2.8.2
  publisher: IBM
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s