apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ibm-spectrum-fusion-ns

resources:
  - namespace.yaml
  - catalog-source.yaml
  - operator.yaml
  - isf-application-operator-sa-patch.yaml