apiVersion: odf.isf.ibm.com/v1
kind: OdfCluster
metadata:
  generation: 1
  name: odfcluster
  namespace: ibm-spectrum-fusion-ns
spec:
  creator: CreatedByFusion
  deviceSets:
    - capacity: 512Gi
      count: 2
      name: fusion-storage
      storageClass: ontap-san
  drConfig:
    enableRegionalDR: true
  encryption:
    clusterWide: true
    keyManagementService: {}
  externalStorage: {}
  mcgOnlyModeSpec: {}
  storageClient: {}
  storageNodes:
    - dl380g9-7.etl6.ocp.rht-labs.com
    - dl380g9-5.etl6.ocp.rht-labs.com
    - dl380g9-6.etl6.ocp.rht-labs.com