apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: isf-operator
spec:
  channel: v2.0
  installPlanApproval: Automatic
  name: isf-operator
  source: ibm-operator-catalog
  sourceNamespace: ibm-spectrum-fusion-ns
---
- apiVersion: operators.coreos.com/v1
  kind: OperatorGroup
  metadata:
    name: ibm-spectrum-fusion
  spec:
    targetNamespaces:
    - ibm-spectrum-fusion-ns
    upgradeStrategy: Default
