apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: kubernetes-nmstate-operator
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  operatorGroup: # optional
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    targetNamespaces:
        - openshift-nmstate
  subscription:
    channel: stable
    name: kubernetes-nmstate-operator
    namespace: openshift-nmstate
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kubernetes-nmstate-operator.4.17.0-202501301304
  versions: 
    - kubernetes-nmstate-operator.4.17.0-202501301304
    - kubernetes-nmstate-operator.4.17.0-202502120148
    - kubernetes-nmstate-operator.4.17.0-202502190034
    - kubernetes-nmstate-operator.4.17.0-202502250404
    - kubernetes-nmstate-operator.4.17.0-202503050235
    - kubernetes-nmstate-operator.4.17.0-202504092035
    - kubernetes-nmstate-operator.4.18.0-202504090803
    - kubernetes-nmstate-operator.4.18.0-202504021503
    - kubernetes-nmstate-operator.4.18.0-202503260133
    - kubernetes-nmstate-operator.4.18.0-202503190933
    - kubernetes-nmstate-operator.4.18.0-202503102003
    - kubernetes-nmstate-operator.4.18.0-202503050303
    - kubernetes-nmstate-operator.4.18.0-202502250802
    - kubernetes-nmstate-operator.4.18.0-202502110432
    - kubernetes-nmstate-operator.4.18.0-202504160308
    - kubernetes-nmstate-operator.4.18.0-202504231304

