apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml        

helmGlobals:
  chartHome: ../../../../.helm-charts

helmCharts:      
  - name: cluster-registration
    releaseName: etl4
    namespace: etl4 