apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: multipath-worker
  labels:
    machineconfiguration.openshift.io/role: worker
spec:    
  config:
    ignition:
      version: 3.4.0    
    # systemd:
    #   units:
    #   - name: multipathd.service
    #     enabled: true
    storage:
      files:
        - contents:
          # defaults {
          # user_friendly_names no
          # max_fds max
          # flush_on_last_del yes
          # queue_without_daemon no
          # dev_loss_tmo infinity
          # fast_io_fail_tmo 5
          # find_multipaths no
          # }
          # # All data in the following section must be specific to your system.
          # blacklist {
          # wwid "SAdaptec*"
          # devnode "^hd[a-z]"
          # devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
          # devnode "^cciss.*"
          # }
          # devices {
          # device {
          # vendor "NETAPP"
          # product "LUN"
          # path_grouping_policy group_by_prio
          # features "2 pg_init_retries 50"
          # no_path_retry queue
          # prio "alua"
          # path_checker tur
          # failback immediate
          # path_selector "round-robin 0"
          # hardware_handler "1 alua"
          # rr_weight uniform
          # rr_min_io 128
          # }
          # }
            source: 'data:text/plain;charset=utf-8;base64,ICAgICAgICAgIGRlZmF1bHRzIHsKICAgICAgICAgIHVzZXJfZnJpZW5kbHlfbmFtZXMgbm8KICAgICAgICAgIG1heF9mZHMgbWF4CiAgICAgICAgICBmbHVzaF9vbl9sYXN0X2RlbCB5ZXMKICAgICAgICAgIHF1ZXVlX3dpdGhvdXRfZGFlbW9uIG5vCiAgICAgICAgICBkZXZfbG9zc190bW8gaW5maW5pdHkKICAgICAgICAgIGZhc3RfaW9fZmFpbF90bW8gNQogICAgICAgICAgZmluZF9tdWx0aXBhdGhzIG5vCiAgICAgICAgICB9CiAgICAgICAgICAjIEFsbCBkYXRhIGluIHRoZSBmb2xsb3dpbmcgc2VjdGlvbiBtdXN0IGJlIHNwZWNpZmljIHRvIHlvdXIgc3lzdGVtLgogICAgICAgICAgYmxhY2tsaXN0IHsKICAgICAgICAgIHd3aWQgIlNBZGFwdGVjKiIKICAgICAgICAgIGRldm5vZGUgIl5oZFthLXpdIgogICAgICAgICAgZGV2bm9kZSAiXihyYW18cmF3fGxvb3B8ZmR8bWR8ZG0tfHNyfHNjZHxzdClbMC05XSoiCiAgICAgICAgICBkZXZub2RlICJeY2Npc3MuKiIKICAgICAgICAgIH0KICAgICAgICAgIGRldmljZXMgewogICAgICAgICAgZGV2aWNlIHsKICAgICAgICAgIHZlbmRvciAiTkVUQVBQIgogICAgICAgICAgcHJvZHVjdCAiTFVOIgogICAgICAgICAgcGF0aF9ncm91cGluZ19wb2xpY3kgZ3JvdXBfYnlfcHJpbwogICAgICAgICAgZmVhdHVyZXMgIjIgcGdfaW5pdF9yZXRyaWVzIDUwIgogICAgICAgICAgbm9fcGF0aF9yZXRyeSBxdWV1ZQogICAgICAgICAgcHJpbyAiYWx1YSIKICAgICAgICAgIHBhdGhfY2hlY2tlciB0dXIKICAgICAgICAgIGZhaWxiYWNrIGltbWVkaWF0ZQogICAgICAgICAgcGF0aF9zZWxlY3RvciAicm91bmQtcm9iaW4gMCIKICAgICAgICAgIGhhcmR3YXJlX2hhbmRsZXIgIjEgYWx1YSIKICAgICAgICAgIHJyX3dlaWdodCB1bmlmb3JtCiAgICAgICAgICBycl9taW5faW8gMTI4CiAgICAgICAgICB9CiAgICAgICAgICB9'
          mode: 420
          overwrite: true
          path: /etc/multipath.conf