{{ if .Values.servicemesh_federation.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sm-intermediate-ca
  namespace: {{ .Release.Name }}
  labels:
    {{- include "cluster-registration.labels" . | nindent 4 }}  
spec:
  isCA: true
  commonName: Intermediate CA
  secretName: intermediate-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: root-ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  encodeUsagesInRequest: true
  usages:
    - signing
    - digital signature
    - cert sign
    - client auth
    - server auth
    - email protection
  dnsNames:
    - istiod.istio-system.svc
    - istiod.istio-system.svc.cluster.local
  subject:
    countries:
      - US
    organizationalUnits:
      - Istio Mesh
      - {{ .Release.Name }}
    organizations:
      - ETL Lab
{{ end }}      