{{ if .Values.mtv_integration.enabled }}
apiVersion: authentication.open-cluster-management.io/v1alpha1
kind: ManagedServiceAccount
metadata:
  name: {{ .Release.Name }}-mtv
  namespace: {{ .Release.Name }}
  labels:
    {{- include "cluster-registration.labels" . | nindent 4 }} 
spec:
  rotation: {}
---
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: {{ .Release.Name }}-mtv
  namespace: {{ .Release.Name }}
  labels:
    {{- include "cluster-registration.labels" . | nindent 4 }}  
spec:
  clusterRole:
    rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]
  clusterRoleBinding:
    subject:
      apiGroup: authentication.open-cluster-management.io
      kind: ManagedServiceAccount
      name: {{ .Release.Name }}-mtv
{{ end }}      