{{ if .Values.acm_virtualization_features.enabled }}
apiVersion: authentication.open-cluster-management.io/v1beta1
kind: ManagedServiceAccount
metadata:
  name: vm-actor
  namespace: {{ .Release.Name }}
  labels:
    app: search
    {{- include "cluster-registration.labels" . | nindent 4 }}
spec:
  rotation: {}
---
apiVersion: rbac.open-cluster-management.io/v1alpha1
kind: ClusterPermission
metadata:
  name: vm-actions
  namespace: {{ .Release.Name }}
  labels:
    app: search
    {{- include "cluster-registration.labels" . | nindent 4 }}
spec:
  clusterRole:
    rules:
      - apiGroups:
          - subresources.kubevirt.io
        resources:
          - virtualmachines/start
          - virtualmachines/stop
          - virtualmachines/restart
          - virtualmachineinstances/pause
          - virtualmachineinstances/unpause
        verbs:
          - update
  clusterRoleBinding:
    subject:
      kind: ServiceAccount
      name: vm-actor
      namespace: open-cluster-management-agent-addon
{{ end }}      