apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  istio-system

resources:
  - ./namespace.yaml
  - ./istio.yaml
  - ./istiocni.yaml
  - ./pod-monitor.yaml
  - ./service-monitor.yaml
  - ./telemetry.yaml
  - github.com/kubernetes-sigs/gateway-api/config/crd?ref=v1.0.0
  - east-west-gateway.yaml
  - federated-services-gateway.yaml