apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../components/node-health-check-configuration

patches:
  - patch: |-
      apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
      kind: FenceAgentsRemediationTemplate
      metadata:
        name: main-remediation
      spec:
        template:
          spec:
            nodeparameters:
              --ip: 
                dl380g9-5.etl6.ocp.rht-labs.com: "10.9.48.215"
                dl380g9-6.etl6.ocp.rht-labs.com: "10.9.48.216"
                dl380g9-7.etl6.ocp.rht-labs.com: "10.9.48.217"