apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: percona-root-ca
spec:
  isCA: true
  commonName: Root CA
  secretName: root-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  encodeUsagesInRequest: true
  subject:
    countries:
      - US
    organizationalUnits:
      - Percona demo
    organizations:
      - ETL Lab  
  usages:
    - crl sign
    - cert sign
    - signing
    - digital signature