kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pr-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ontap-san
  volumeMode: Block