apiVersion: cdi.kubevirt.io/v1beta1
kind: DataImportCron
metadata:
  annotations:
    cdi.kubevirt.io/storage.bind.immediate.requested: 'true'
    cdi.kubevirt.io/storage.import.storageClass: ontap-san
  name: infinibox-demo-7.3.11.0-cbdev-7.3.11
  labels:
    kubevirt.io/dynamic-credentials-support: 'true'
spec:
  garbageCollect: Outdated
  managedDataSource: infinibox-demo-7.3.11.0-cbdev-7.3.11
  schedule: 48 0/12 * * *
  template:
    metadata: {}
    spec:
      source:
        registry:
          url: 'docker://quay.io/raffaelespazzoli/infinibox-demo-7.3.11.0-cbdev-7.3.11:20250206-1'
          secretRef: raffa-quay
      storage:
        resources:
          requests:
            storage: 160Gi
    status: {}
# ---
# apiVersion: snapshot.storage.k8s.io/v1
# kind: VolumeSnapshot
# metadata:
#   name: infinibox-demo-7.3.11.0-cbdev-7.3.11-snapshot
# spec:
#   source:
#     persistentVolumeClaimName: infinibox-demo-7.3.11.0-cbdev-7.3.11
#   volumeSnapshotClassName: trident-snapshotclass
#---  
# apiVersion: cdi.kubevirt.io/v1beta1
# kind: DataSource
# metadata:
#   name: infinibox-demo-7.3.11.0-cbdev-7.3.11
# spec:
#   source:
#     snapshot:
#       name: infinibox-demo-7.3.11.0-cbdev-7.3.11
#       namespace: infinibox-appliance