apiVersion: v1
kind: Service
metadata:
  name: infinibox-ssh
spec:
  selector:
    kubevirt.io/vm: vm-ibox
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: infinibox-http
spec:
  selector:
    kubevirt.io/vm: vm-ibox
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 433
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80      
  type: ClusterIP
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: infinibox
spec:
  to:
    kind: Service
    name: infinibox-https
    weight: 100
  port:
    targetPort: 443
  wildcardPolicy: None
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: infinibox-http
spec:
  to:
    kind: Service
    name: infinibox-http
    weight: 100
  port:
    targetPort: 80
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect       
