apiVersion: agent-install.openshift.io/v1beta1
kind: AgentServiceConfig
metadata:
 name: agent
spec:
  databaseStorage:
    storageClassName: ontap-nas
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
  filesystemStorage:
    storageClassName: ontap-san
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  imageStorage:
    storageClassName: ontap-nas
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 100Gi
