kind: ConfigMap
apiVersion: v1
metadata:
  name: console-mce-config
  namespace: multicluster-engine
  annotations:
    argocd.argoproj.io/sync-options: Delete=false,ServerSideApply=true  
data:
  LOG_LEVEL: info
  ansibleIntegration: disabled
  awsPrivateWizardStep: enabled
  singleNodeOpenshift: disabled