apiVersion: infoscale.veritas.com/v1
kind: InfoScaleCluster
metadata:
  name: infoscalecluster-dev
spec:
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/master
        operator: Exists
  encrypted: false
  sameEncKey: false
  enableScsi3pr: false
  isSharedStorage: false
  version: 8.0.400
  clusterID: 21342