      
projects: {}

applications:  

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl7/overlays/nmstate-configuration

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl7/overlays/trident-configuration

  # ibm-fusion-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: ibm-spectrum-fusion-ns
  #   source:
  #     path: clusters/etl7/overlays/ibm-fusion-configuration
  #   extraFields: |
  #     ignoreDifferences:
  #       - group: 'service.isf.ibm.com'
  #         jsonPointers:
  #           - /spec/doInstall
  #         kind: FusionServiceInstance                       