      
projects: {}

applications:  

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: '16'      
    source:
      path: clusters/etl7/overlays/openshift-config

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl7/overlays/nmstate-configuration

  metallb-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: metallb-system
    source:
      path: clusters/etl7/overlays/metallb-configuration      

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl7/overlays/trident-configuration


  bookinfo:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: bookinfo
    source:
      path: components/bookinfo                               