      
projects: {}

applications:  

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: '16'      
    source:
      path: clusters/etl7/overlays/openshift-config

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl7/overlays/nmstate-configuration

  metallb-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: metallb-system
    source:
      path: clusters/etl7/overlays/metallb-configuration      

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl7/overlays/trident-configuration

  # ibm-fusion-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: ibm-spectrum-fusion-ns
  #   source:
  #     path: clusters/etl7/overlays/ibm-fusion-configuration
  #   extraFields: |
  #     ignoreDifferences:
  #       - group: 'service.isf.ibm.com'
  #         jsonPointers:
  #           - /spec/doInstall
  #         kind: FusionServiceInstance

  fusion-access-for-san-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/fusion-access-for-san-operator

  fusion-access-for-san-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-fusion-access   
    source:
      path: components/fusion-access-for-san-configuration   

  infinidat-appliance:
    annotations:
      argocd.argoproj.io/sync-wave: '25'     
    source:
      path: clusters/etl7/overlays/infinidat-appliance                         