apiVersion: service.isf.ibm.com/v1
kind: FusionServiceInstance
metadata:
  name:  odfmanager
spec:
  creator: User
  doInstall: true
  parameters:
  - name: namespace
    provided: false
    value: openshift-storage
  - name: creator
    provided: false
    value: Fusion
  - name: backingStorageType
    provided: true
    value: Dynamic
  - name: autoUpgrade
    provided: false
    value: "true"
  - name: enableLVMStorage
    provided: true
    value: "false"
  serviceDefinition: data-foundation-service
  triggerUpdate: false