apiVersion: odf.isf.ibm.com/v1
kind: OdfCluster
metadata:
  name: odfcluster
spec:
  creator: CreatedByFusion
  deviceSets:
    - capacity: 512Gi
      count: 2
      name: fusion-storage
      storageClass: ontap-san
  drConfig:
    enableRegionalDR: true
  encryption:
    clusterWide: true
    keyManagementService: {}
  externalStorage: {}
  mcgOnlyModeSpec: {}
  storageClient: {}
  storageNodes: []