apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    description: Network 2522 via OVS Bridge
  name: vlan-2522
  namespace: default
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "vlan-2522",
      "type": "ovn-k8s-cni-overlay",
      "topology": "localnet",
      "netAttachDefName": "default/vlan-2522",
      "vlanID": 2522,
      "mtu": 1500,
      "subnets": "10.10.1.0/24"
    }