apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: kubevirt-hyperconverged
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  operatorGroup: # optional
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    targetNamespaces:
        - openshift-cnv
  subscription:
    channel: stable
    name: kubevirt-hyperconverged
    namespace: openshift-cnv
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: kubevirt-hyperconverged-operator.v4.17.4
  versions: 
    - kubevirt-hyperconverged-operator.v4.17.4
    - kubevirt-hyperconverged-operator.v4.17.5
    - kubevirt-hyperconverged-operator.v4.17.7
    - kubevirt-hyperconverged-operator.v4.18.1
    - kubevirt-hyperconverged-operator.v4.18.2