apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openshift-power-monitoring

resources:
- ../../../../components/power-monitoring-configuration

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
- name: redfish-secret
  files:
  - redfish.csv