apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: example.com
  namespace: sso
  labels:
    app: sso
spec:
  realm:
    id: example.com
    realm: example.com
    enabled: true
    displayName: example.com realm
  instanceSelector:
    matchLabels:
      app: sso