apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sso

resources:
  - keycloak.yaml
  - clients.yaml
  - keycloak-realm.yaml
  - link.yaml
  - users.yaml
  - groups.yaml
  - oauth-secret-policy.yaml
  - rbac.yaml