apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: ibm-spectrum-scale
  namespace: ibm-spectrum-scale
spec:
  pmCollector:
    storageClass: "ontap-nas"
  daemon:
    clusterProfile:
      controlSetxattrImmutableSELinux: "yes"
      enforceFilesetQuotaOnRoot: "yes"
      ignorePrefetchLUNCount: "yes"
      initPrefetchBuffers: "128"
      maxblocksize: 16M
      prefetchPct: "25"
      prefetchTimeout: "30"
    nodeSelector:
      scale.spectrum.ibm.com/daemon-selector: ""
    roles:
    - limits: {}	
      name: client	
      profile: {}    
      resources:
        cpu: "2"
        memory: 4Gi
    - limits: {}	
      name: storage	
      profile: {}    
      resources:
        cpu: "2"
        memory: 8Gi
  license:
    accept: true
    license: data-management
  networkPolicy: {}