apiVersion: scale.spectrum.ibm.com/v1beta1
kind: LocalDisk
metadata:
  labels:
    app.kubernetes.io/instance: ibm-spectrum-scale
    app.kubernetes.io/name: cluster
  name: shared-lun
  namespace: ibm-spectrum-scale
spec:
  device: /dev/sdc
  node: openshift-ctlplane-0
  # set below only during testing
  existingDataSkipVerify: true