apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: manage-vm-dr
spec:
  rules:
    - name: manage-vm-dr
      skipBackgroundRequests: false
      context:
      - name: DRConfigMap
        configMap:
          name: cluster-dr-role
          namespace: openshift-gitops      
      match:
        any:
        - resources:
            kinds:
            - VirtualMachine
            selector:
              matchLabels:
                dr-managed: "true"
      mutate:
        patchStrategicMerge:
          spec:
            running: '{{(DRConfigMap.data.{{request.object.metadata.labels.tier}}|parse_yaml(@).workloads.${CLUSTER_NAME}) == "active"}}'
---            
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: manage-hitachi-volumes-dr
spec:
  rules:
  - name: manage-hitachi-volumes-dr
    skipBackgroundRequests: false
    context:
    - name: DRConfigMap
      configMap:
        name: cluster-dr-role
        namespace: openshift-gitops
    - name: volumeStatusLookupTable
      variable:
        value: |-
          non-replicated: split
          replicated-primary: none
          replicated-secondary: none 
          "true": primary
          "false": secondary        
    match:
      any:
      - resources:
          kinds:
          - Replication
          selector:
            matchLabels:
              dr-managed: "true"
    mutate:
      patchStrategicMerge:
        spec:
          desiredPairState: '{{parse_yaml(volumeStatusLookupTable).{{(DRConfigMap.data.{{request.object.metadata.labels.tier}}|parse_yaml(@).volumes.${CLUSTER_NAME})}}}}'
          replicationAttribute: '{{parse_yaml(volumeStatusLookupTable).{{starts_with(DRConfigMap.data.{{request.object.metadata.labels.tier}}|parse_yaml(@).volumes.${CLUSTER_NAME} , "replicated")|to_string(@)}}}}'
