apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: manager-vm-dr
spec:
  rules:
    - name: manager-vm-dr
      skipBackgroundRequests: false
      context:
      - name: DRConfigMap
        configMap:
          name: cluster-dr-role
          namespace: openshift-gitops      
      match:
        any:
        - resources:
            kinds:
            - VirtualMachine
            selector:
              matchLabels:
                dr-managed: "true"
      mutate:
        patchStrategicMerge:
          spec:
            running: '{{(DRConfigMap.data.{{request.object.metadata.labels.tier}}|parse_yaml(@).${CLUSTER_NAME}) == "active"}}'