securityContext: 
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

service:
  # Type of service. Set to "None" to disable the service entirely
  type: LoadBalancer
  ports:
  - name: status-port
    port: 15021
    protocol: TCP
    targetPort: 15021
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  annotations:
    external-dns.alpha.kubernetes.io/hostname: '*.mesh-udn.vips.${CLUSTER_BASE_DOMAIN}'     
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  externalTrafficPolicy: ""
  externalIPs: []