apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../cluster-versions.yaml  
  - ../../groups/all

helmGlobals:
  chartHome: ../../.helm-charts

helmCharts:
- name: argocd-app-of-app
  valuesFile: values.yaml
  namespace: openshift-gitops

patches:
- patch: |-
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cluster-versions
      namespace: openshift-gitops
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "acm-policies"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "acm-policies"


replacements:
- source:
    version: v1
    kind: ConfigMap
    name: cluster-versions
    fieldPath: data.hub
  targets:
  - select:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    fieldPaths:
    - spec.source.targetRevision