      
projects: {}

applications: 

# ACM
  acm-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: open-cluster-management
    source:
      path: components/acm-operator

  acm-instance:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: components/acm-instance


  acm-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    source:
      path: components/acm-configuration  

# Storage

  trident-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: netapp-trident
    source:
      path: misc4.0/etl/etl4/components/trident-operator

  trident-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: misc4.0/etl/etl4/components/trident-configuration

  minio-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5' 
    destination:
      namespace: minio-operator           
    source:
      path: misc4.0/etl/etl4/components/minio-operator      


                          