apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: trilio-s3-target
spec:
  enableBrowsing: true
  type: ObjectStore
  vendor: AWS
  objectStoreCredentials:
    url: "http://trilio-bucket-trilio-system.apps.hub2.ocp.rht-labs.com/"
    region: minio
    bucketName: trilio
    credentialSecret:
      apiVersion: v1	
      kind: Secret      
      name: trilio-target
      namespace: trilio-system
  thresholdCapacity: 500Gi