      
projects: {}

applications: 

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl4/overlays/nmstate-configuration

  metallb-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: metallb-system
    source:
      path: clusters/etl4/overlays/metallb-configuration      

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl4/overlays/trident-configuration

  # ibm-fusion-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: ibm-spectrum-fusion-ns
  #   source:
  #     path: clusters/etl7/overlays/ibm-fusion-configuration
  #   extraFields: |
  #     ignoreDifferences:
  #       - group: 'service.isf.ibm.com'
  #         jsonPointers:
  #           - /spec/doInstall
  #         kind: FusionServiceInstance      

# HA

  node-health-check-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-workload-availability
    source:
      path: clusters/etl4/overlays/node-health-check-configuration   

# Observability

  power-monitoring-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl4/overlays/power-monitoring-configuration       


# VDI

  vault:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: vault      
    source:
      path: clusters/etl4/overlays/vault
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/volumeClaimTemplates
          kind: StatefulSet      

  # rhsso-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   source:
  #     path: clusters/etl4/overlays/rhsso-operator

  # rhsso-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   source:
  #     path: clusters/etl4/overlays/rhsso-configuration

  guacamole:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: guacamole      
    source:
      path: clusters/etl4/overlays/guacamole

  ldap:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: ldap      
    source:
      path: clusters/etl4/overlays/ldap     

  rhsso-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'     
    source:
      path: clusters/etl4/overlays/rhsso-operator  

  rhsso-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'     
    source:
      path: clusters/etl4/overlays/rhsso-configuration                 


# Infinidat

  infinidat-appliance-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'     
    source:
      path: clusters/etl4/overlays/infinidat-appliance

# Infinidat

  persistent-reservations:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'     
    source:
      path: clusters/etl4/overlayspersistent-reservations      