      
projects: {}

applications: 

  openshift-config:
    annotations:
      argocd.argoproj.io/sync-wave: '16'      
    source:
      path: clusters/etl4/overlays/openshift-config

# Networking

  nmstate-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: clusters/etl4/overlays/nmstate-configuration

  metallb-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: metallb-system
    source:
      path: clusters/etl4/overlays/metallb-configuration      

# Storage

  trident-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: netapp-trident
    source:
      path: clusters/etl4/overlays/trident-configuration          


# VDI

  vault:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: vault      
    source:
      path: clusters/etl4/overlays/vault
    extraFields: |
      ignoreDifferences:
        - group: 'apps'
          jsonPointers:
            - /spec/volumeClaimTemplates
          kind: StatefulSet      

  guacamole:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: guacamole      
    source:
      path: clusters/etl4/overlays/guacamole

  rhsso-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'     
    source:
      path: clusters/etl4/overlays/rhsso-operator  

  rhsso-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'     
    source:
      path: clusters/etl4/overlays/rhsso-configuration                       

  test-udn:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    source:
      path: clusters/etl4/overlays/test-udn    

# observability

  openshift-tempo-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-tempo-operator
    source:
      path: components/openshift-tempo-operator

  openshift-tempo-instance:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-tempo-instance
    source:
      path: components/openshift-tempo-instance

# service mesh

  servicemesh-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'     
    source:
      path: components/openshift-servicemesh-operator   

  servicemesh-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'     
    source:
      path: components/openshift-servicemesh-configuration 

  kiali-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-kiali-operator
    source:
      path: components/kiali-operator

  kiali-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: istio-system
    source:
      path: components/kiali-configuration                