apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: vm-dr-test
spec:
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: etl6-to-etl7
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: vm-dr-test
    namespace: openshift-gitops
  preferredCluster: etl6
  pvcSelector:
    matchLabels:
      app.kubernetes.io/component: storage

