apiVersion: charts.kubecost.com/v1alpha1
kind: CostAnalyzer
metadata:
  name: cluster
  namespace: kubecost-operator
spec:
  clusterController:
    image:
      repository: registry.connect.redhat.com/kubecost/kubecost-cluster-controller@sha256
      tag: 1a6f11dcd7341ab3f24eba23ec06c7b75646a534a7ed960153601806425469d1
  forecasting:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-modeling@sha256:8f59f8fd8696964c1b5322ca79fae78befe97323fa56c2b509bdcc67ee4c0edd'
  global:
    platforms:
      openshift:
        createMonitoringClusterRoleBinding: true
        createMonitoringResourceReaderRoleBinding: true
        enabled: true
        scc:
          clusterController: true
          networkCosts: true
          nodeExporter: true
    prometheus:
      enabled: false
      fqdn: 'https://prometheus-k8s.openshift-monitoring.svc.cluster.local:9091'
      kubeRBACProxy: true
  grafana:
    image:
      repository: registry.redhat.io/rhel9/grafana@sha256
      tag: 9f71de028c18034e07a8d15dac13ef68afb91cb899b9e8e7d39703547dd0eac1
    sidecar:
      image:
        repository: quay.io/kiwigrid/k8s-sidecar@sha256
        tag: d3749777d5bedf62549b452a7e2ccb205da53588dc7f04927efc75d0da5b6d23
  kubecostAggregator:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-cost-model@sha256:1b9c9f309e6f41addc7fb6418724a6a6b08486290e31fe1f614efc649874bcef'
  kubecostFrontend:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-frontend@sha256:f9b2196dc6ac017b8074f8fe40f1a58e7a2630282c5b7a019ca9f3dbdb670dc8'
  kubecostModel:
    fullImageName: 'registry.connect.redhat.com/kubecost/kubecost-cost-model@sha256:1b9c9f309e6f41addc7fb6418724a6a6b08486290e31fe1f614efc649874bcef'
  networkCosts:
    image:
      repository: registry.connect.redhat.com/kubecost/kubecost-network-costs@sha256
      tag: c444d475be4f1aa36680bd84358e1e07303dcfe5d13a95544ad9e59f80d4a5f0
  prometheusRule:
    enabled: true
  serviceMonitor:
    enabled: true