apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: kubecost
spec:
  to:
    name: cluster-cost-analyzer
    weight: 100
    kind: Service
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  port:
    targetPort: tcp-frontend