apiVersion: v1
kind: ServiceAccount
metadata:
  name: wasp
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wasp-cluster-admin
subjects:
  - kind: ServiceAccount
    name: wasp
    namespace: wasp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wasp-privileged
subjects:
  - kind: ServiceAccount
    name: wasp
    namespace: wasp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'