apiVersion: kepler.system.sustainable.computing.io/v1alpha1
kind: Kepler
metadata:
  name: kepler
spec:
  exporter:
    deployment:
      port: 9103 
      nodeSelector:
        kubernetes.io/os: linux 
      tolerations: 
      - key: ""
        operator: "Exists"
        value: ""
        effect: ""