apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: servicemesh-federation-policy
  # Must be a recognized policy namespace on the hub
  namespace: acm-policies
spec:
  remediationAction: enforce
  disabled: false
  hubTemplateOptions:
    serviceAccountName: policy-admin
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: servicemesh-federation-policy
        spec:
          remediationAction: enforce
          severity: low
          object-templates-raw: |-
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: root-ca
                  namespace: 'istio-system'
                type: kubernetes.io/tls
                data:
                  tls.crt: {{hub (index (lookup "v1" "Secret" "istio-system" "root-ca").data "tls.crt") hub}}
                  tls.key: {{hub (index (lookup "v1" "Secret" "istio-system" "root-ca").data "tls.key") hub}}
                  ca.crt: {{hub (index (lookup "v1" "Secret" "istio-system" "root-ca").data "ca.crt") hub}}
            - complianceType: mustonlyhave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: cacerts
                  namespace: 'istio-system'
                type: Opaque
                data:    
                  ca-cert.pem: {{ (index (lookup "v1" "Secret" "istio-system" "intermediate-ca").data "tls.crt") }}
                  ca-key.pem: {{ (index (lookup "v1" "Secret" "istio-system" "intermediate-ca").data "tls.key") }}
                  root-cert.pem: {{ (index (lookup "v1" "Secret" "istio-system" "root-ca").data "tls.crt") }}
                  cert-chain.pem: {{ (list ((index (lookup "v1" "Secret" "istio-system" "intermediate-ca").data "tls.crt") | base64dec) ((index (lookup "v1" "Secret" "istio-system" "root-ca").data "tls.crt") | base64dec)) | join "\n" | base64enc }}
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: servicemesh-federation-placement
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            servicemesh-federation: "enabled"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: servicemesh-federation-binding
  namespace: acm-policies
subjects:
  - kind: Policy
    apiGroup: policy.open-cluster-management.io
    name: servicemesh-federation-policy
placementRef:
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
  name: servicemesh-federation-placement