applications:     

# Basic

  openshift-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '16'      
    source:
      path: groups/prod/overlays/openshift-config


## Virtualization

  openshift-virtualization:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-cnv
    source:
      path: components/openshift-virtualization-operator

  hyperconverged-instance:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-cnv
    source:
      path: components/openshift-virtualization-instance

  descheduler-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
        namespace: openshift-kube-descheduler-operator
    source:
      path: components/descheduler-operator  

  descheduler-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
        namespace: openshift-kube-descheduler-operator      
    source:
      path: components/descheduler-configuration      

# HA

  node-health-check-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-workload-availability
    source:
      path: components/node-health-check-operator     

## Storage

  # ibm-fusion-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   destination:
  #     namespace: ibm-spectrum-fusion-ns      
  #   source:
  #     path: components/ibm-fusion-operator

  # ibm-fusion-storage-system:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '25'
  #   destination:
  #     namespace: openshift-storage
  #   source:
  #     path: components/ibm-fusion-storage-system            

## Backup and DR

  oadp-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-adp
    source:
      path: components/oadp-operator

  oadp-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-adp
    source:
      path: components/oadp-configuration

  trilio-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: trilio-system
    source:
      path: components/trilio-operator

  trilio-instance:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: trilio-system
    source:
      path: components/trilio-instance


  trilio-configuration:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: trilio-system
    source:
      path: components/trilio-configuration
    extraFields: |
      ignoreDifferences:
        - group: 'triliovault.trilio.io'
          jsonPointers:
            - /spec/backupConfig/target/resourceVersion
            - /spec/backupConfig/target/uid
          kind: BackupPlan             

# Observability

  power-monitoring-operator:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: openshift-operators
    source:
      path: components/power-monitoring-operator



      