applications:     

# Basic



  kyverno-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
      argocd.argoproj.io/compare-options: IgnoreExtraneous,ServerSideDiff=true
    source:
      path: components/kyverno-operator   

  kyverno-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: groups/prod/overlays/kyverno-configuration      


## Virtualization

  openshift-virtualization:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/openshift-virtualization-operator

  hyperconverged-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-cnv
    source:
      path: components/openshift-virtualization-instance

  descheduler-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/descheduler-operator  

  descheduler-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
        namespace: openshift-kube-descheduler-operator      
    source:
      path: components/descheduler-configuration     
    
    
    # disabled because not gitops friendly
  # wasp-agent:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   destination:
  #       namespace: wasp     
  #   source:
  #     path: components/wasp-agent

# HA

  node-health-check-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/node-health-check-operator

  node-health-check-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: openshift-workload-availability
    source:
      path: components/node-health-check-configuration   

## Storage

  # ibm-fusion-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   destination:
  #     namespace: ibm-spectrum-fusion-ns      
  #   source:
  #     path: components/ibm-fusion-operator

  # ibm-fusion-storage-system:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '25'
  #   destination:
  #     namespace: openshift-storage
  #   source:
  #     path: components/ibm-fusion-storage-system            

## Backup and DR

  # oadp-operator:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '5'
  #   source:
  #     path: components/oadp-operator

  # oadp-configuration:
  #   annotations:
  #     argocd.argoproj.io/compare-options: IgnoreExtraneous
  #     argocd.argoproj.io/sync-wave: '15'
  #   destination:
  #     namespace: openshift-adp
  #   source:
  #     path: components/oadp-configuration

  trilio-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/trilio-operator

  trilio-instance:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: trilio-system
    source:
      path: components/trilio-instance


  trilio-configuration:
    enableAutoSync: false
    annotations:
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: trilio-system
    source:
      path: components/trilio-configuration
    extraFields: |
      ignoreDifferences:
        - group: 'triliovault.trilio.io'
          jsonPointers:
            - /spec/objectStoreCredentials/credentialSecret/resourceVersion
            - /spec/objectStoreCredentials/credentialSecret/uid
          kind: Target             

# Observability

  power-monitoring-operator:
    annotations:
      argocd.argoproj.io/sync-wave: '5'
    source:
      path: components/power-monitoring-operator

  power-monitoring-configuration:
    annotations:
      argocd.argoproj.io/sync-wave: '15'
    source:
      path: components/power-monitoring-configuration           