apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
    ocs.openshift.io/clusterIsDisasterRecoveryTarget: "true"
  name: ocs-storagecluster
spec:
  arbiter: {}
  encryption:
    keyRotation:
      schedule: '@weekly'
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephNonResilientPools: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
    cephRBDMirror: {}
    cephToolbox: {}
  network:
    connections:
      encryption: {}
    multiClusterService: {}
  nfs:
    enable: true
  nodeTopologies: {}
  resourceProfile: balanced
  storageDeviceSets:
  - config: {}
    count: 1
    dataPVCTemplate:
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 512Gi
        storageClassName: ontap-san
        volumeMode: Block
      status: {}
    name: ocs-deviceset-ontap-san
    placement: {}
    portable: true
    preparePlacement: {}
    replica: 3
    resources: {}