kind: ServiceAccount
apiVersion: v1
metadata:
  name: default
  namespace: openshift-mtv
  annotations: 
    argocd.argoproj.io/sync-options: ServerSideApply=true
imagePullSecrets:
- name: quay-pull-secret    