apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-monitoring-config
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true  
data:
  config.yaml: |
    enableUserWorkload: true
    alertmanagerMain:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    prometheusK8s:
      additionalAlertmanagerConfigs:	
      - apiVersion: v2	
        bearerToken:	
          key: token	
          name: observability-alertmanager-accessor	
        scheme: https	
        staticConfigs:	
        - alertmanager-open-cluster-management-observability.apps.hub2.ocp.rht-labs.com	
        tlsConfig:	
          ca:	
            key: service-ca.crt	
            name: hub-alertmanager-router-ca	
          insecureSkipVerify: false	
      externalLabels:	
        managed_cluster: 234ce2bd-1b5c-4ea5-a29d-26e1bb4c1bac    
      volumeClaimTemplate:
        spec:
          storageClassName: ontap-nas
          resources:
            requests:
              storage: 100Gi    
      resources:
        limits:
          memory: 32Gi
        requests:
          cpu: 200m
          memory: 8Gi
    thanosQuerier:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    prometheusOperator:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    metricsServer:
      resources:
        limits:
          memory: 500Mi      
        requests:
          cpu: 10m
          memory: 50Mi
    kubeStateMetrics:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    telemeterClient:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    openshiftStateMetrics:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    nodeExporter:
      collectors:	
        buddyinfo: {}	
        cpufreq: {}	
        ksmd: {}	
        mountstats: {}	
        netclass: {}	
        netdev: {}	
        processes: {}	
        systemd: {}	
        tcpstat: {}    
      resources:
        limits:
          memory: 150Mi
        requests:
          cpu: 20m
          memory: 50Mi
    monitoringPlugin:
      resources:
        limits:
          memory: 1Gi
        requests:
          cpu: 200m
          memory: 500Mi
    prometheusOperatorAdmissionWebhook:
      resources:
        limits:
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 50Mi