apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acmo
      endpoint: minio.open-cluster-management-observability.svc.cluster.local
      insecure: true
      access_key: acmo
      secret_key: acmoacmo