apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../components/node-health-check-configuration

patches:
  - patch: |-
      apiVersion: fence-agents-remediation.medik8s.io/v1alpha1
      kind: FenceAgentsRemediationTemplate
      metadata:
        name: main-remediation
      spec:
        template:
          spec:
            nodeparameters:
              --ip: 
                x240m5-11.${CLUSTER_BASE_DOMAIN}: "10.9.48.111"
                x240m5-12.${CLUSTER_BASE_DOMAIN}: "10.9.48.112"
                x240m5-13.${CLUSTER_BASE_DOMAIN}: "10.9.48.113"