apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: replace-mac-address-policy
  annotations:
    policies.kyverno.io/title: Replace mac address
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.8.1
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: VirtualMachine
    policies.kyverno.io/description: >-
      This policy replaces the mac address of a VM from the Vmware domain (00:50:56:xx:yy:zz) to the Openshift Virt domain (02:cd:1b:xx:yy:zz)     
spec:
  rules:
  - name: macaddress
    match:
      any:
      - resources:
          kinds:
          - VirtualMachine
          selector:
            matchLabels:
              replace-mac: "true"             
    mutate:
      foreach:
      - list: "request.object.spec.template.spec.domain.devices.interfaces"
        preconditions:
          all:
          - key: "{{ element.macAddress || '' }}"
            operator: Equals
            value: 00:50:56:*           
        patchesJson6902: |-
          - path: /spec/template/spec/domain/devices/interfaces/{{elementIndex0}}/macAddress
            op: replace
            value: "{{ replace('{{element.macAddress}}', '00:50:56', '02:cd:1b', `1`) }}"  


                        