apiVersion: v1
kind: Service
metadata:
  name: core-dns-tcp
  annotations:
    metallb.io/allow-shared-ip: "coredns"
spec:
  type: LoadBalancer
  ports:
    - name: dnstcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app.kubernetes.io/instance: kuadrant
    app.kubernetes.io/name: coredns
---
apiVersion: v1
kind: Service
metadata:
  name: coredns-udp
  annotations:
    metallb.io/allow-shared-ip: "coredns"
spec:
  type: LoadBalancer
  ports:
    - name: dnsudp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app.kubernetes.io/instance: kuadrant
    app.kubernetes.io/name: coredns