apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: cluster-kube-descheduler-operator
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  operatorGroup: # optional
    name: cluster-kube-descheduler-operator
    namespace: openshift-kube-descheduler-operator
    targetNamespaces:
        - openshift-kube-descheduler-operator
  subscription:
    channel: stable
    name: cluster-kube-descheduler-operator
    namespace: openshift-kube-descheduler-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: clusterkubedescheduleroperator.v5.1.1
  versions: 
    - clusterkubedescheduleroperator.v5.1.1
    - clusterkubedescheduleroperator.v5.1.2