apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-workload-availability

resources:
  - namespace.yaml
  - far-operator.yaml
  - nhc-operator.yaml
  - node-maintenance-operator.yaml