apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: node-healthcheck-operator
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  subscription:
    channel: stable
    name: node-healthcheck-operator
    namespace: openshift-workload-availability
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: node-healthcheck-operator.v0.9.0
  versions: 
    - node-healthcheck-operator.v0.9.0