apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml


helmCharts:      
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    repo: https://kyverno.github.io/kyverno
    valuesInline:
      config:
        webhooks: [{"namespaceSelector":{"matchExpressions":[{"key":"openshift.io/cluster-monitoring","operator":"NotIn","values":["true"]}]}}] 