apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace.yaml
  - ./rbac.yaml


helmCharts:      
  - name: kyverno
    releaseName: kyverno
    namespace: kyverno
    repo: https://kyverno.github.io/kyverno
    includeCRDs: true
    valuesInline:
      excludeKyvernoNamespace: true
      config:
        webhooks: {"namespaceSelector":{"matchExpressions":[{"key":"openshift.io/cluster-monitoring","operator":"NotIn","values":["true"]}]}}
      admissionController:
        initContainer:
          securityContext: null
        container:
          securityContext: null
      backgroundController:
        securityContext: null
      cleanupController:
        securityContext: null
      reportsController:
        securityContext: null
      webhooksCleanup:
        securityContext: null  