---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: migration
spec:
  targetNamespaces:
    - openshift-mtv
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mtv-operator
spec:
  channel: release-v2.7
  installPlanApproval: Automatic
  name: mtv-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace    