apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../components/ibm-fusion-configuration

patches:
  - patch: |-
      apiVersion: odf.isf.ibm.com/v1
      kind: OdfCluster
      metadata:
        name: odfcluster
      spec:
        storageNodes:
        - dl380g9-5.etl6.ocp.rht-labs.com
        - dl380g9-6.etl6.ocp.rht-labs.com
        - dl380g9-7.etl6.ocp.rht-labs.com  