apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: udn-l3
  namespace: test-udn-l3
spec:
  topology: Layer3
  layer3: 
    role: Primary 
    subnets:
      - cidr: 10.150.0.0/16
        hostSubnet: 24