apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: openshift-fusion-access-operator
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  operatorGroup: # optional
    name: openshift-fusion-access-operator
    namespace: openshift-fusion-access
  subscription:
    channel: alpha
    name: openshift-fusion-access-operator
    namespace: openshift-fusion-access
    source: test-fusion-access-operator
    sourceNamespace: openshift-marketplace
    startingCSV: openshift-fusion-access-operator.v0.0.13
  versions: 
    - openshift-fusion-access-operator.v0.0.13
    - openshift-fusion-access-operator.v0.0.14
    - openshift-fusion-access-operator.v0.0.15
    - openshift-fusion-access-operator.v0.0.16
    - openshift-fusion-access-operator.v0.0.21