apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: web-terminal
  namespace: open-cluster-management-policies
spec:
  upgradeApproval: Automatic
  complianceConfig:
    catalogSourceUnhealthy: Compliant
    deploymentsUnavailable: NonCompliant
    upgradesAvailable: Compliant
  complianceType: musthave
  remediationAction: enforce
  removalBehavior:
    clusterServiceVersions: Delete
    customResourceDefinitions: Keep
    operatorGroups: DeleteIfUnused
    subscriptions: Delete
  severity: medium
  subscription:
    channel: fast
    name: web-terminal
    namespace: web-terminal-operator
    source: redhat-operators
    sourceNamespace: openshift-marketplace
    startingCSV: web-terminal.v1.12.1
  versions: 
    - web-terminal.v1.12.1
    - web-terminal.v1.12.1-0.1743657317.p
    - web-terminal.v1.12.1-0.1745393748.p