apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-adp

resources:

  - rbac.yaml
  - credentials-velero-secret.yaml
  - data-protection.yaml
  - backup-schedule.yaml
  - service-monitor.yaml
  - prometheus-rule.yaml
  - routes.yaml
  - link.yaml


helmCharts:
  - name: vui
    repo: https://seriohub.github.io/velero-helm/
    releaseName: velero-ui
    namespace: openshift-adp
    valuesFile: vui-values.yaml 

patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: velero-ui-vui-ingress
  $patch: delete           