apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 00-master-ibm-spectrum-scale-kernel-devel
spec:
  config:
    ignition:
      version: 3.2.0
  extensions:
  - kernel-devel