tenant:
  configSecret:
    name: oadp-env-configuration
    accessKey: oadp
    secretKey: oadpoadp
  configuration:
    name: oadp-env-configuration
  name: oadp
  pools:
    - name: pool-0
      servers: 1
      storageClassName: lvms-vg1
      # these values are not recommended in production. They are here just to keep the costs constrained.
      volumesPerServer: 1
      size: 100Gi
  buckets:
    - name: oadp
      objectLock: false
  certificate:
    requestAutoCert: false
